#pragma once

#include <string>
#include <cstdint>
#include <cstddef>

#include <wolfssl/options.h>  // generated by configure; MUST precede other wolfssl headers
#include <wolfssl/ssl.h>
#include <wolfssl/wolfio.h>   // WOLFSSL_CBIO_ERR_* callback return codes

#include "net_io.h"
#include "log.h"

namespace dicker {
struct TlsSession {
  WOLFSSL_CTX* ctx = nullptr;
  WOLFSSL* ssl = nullptr;
  net::socket_t fd = net::INVALID;

  TlsSession() = default;
  TlsSession(const TlsSession&) = delete;
  TlsSession& operator=(const TlsSession&) = delete;

  ~TlsSession() {
    if (this->ssl != nullptr) {
      wolfSSL_free(this->ssl);
    }
    if (this->ctx != nullptr) {
      wolfSSL_CTX_free(this->ctx);
    }
  }

  // wolfSSL hands every outbound record to this callback: it is the single
  // choke point for bytes going to the wire. This is where ClientHello / TCP
  // fragmentation for DPI evasion belongs -- split the first flight so the SNI
  // extension straddles two segments. For now it is a straight pass-through.
  static int ioSend(WOLFSSL* ssl, char* buf, int sz, void* vctx) {
    (void)ssl;
    TlsSession* self = static_cast<TlsSession*>(vctx);

    if (net::sendAll(self->fd, buf, static_cast<size_t>(sz))) {
      return sz;
    }
    return WOLFSSL_CBIO_ERR_GENERAL;
  }

  static int ioRecv(WOLFSSL* ssl, char* buf, int sz, void* vctx) {
    (void)ssl;
    TlsSession* self = static_cast<TlsSession*>(vctx);

    int n = net::tcpRecv(self->fd, buf, static_cast<size_t>(sz), 0);

    if (n > 0) {
      return n;
    }
    if (n == 0) {
      return WOLFSSL_CBIO_ERR_CONN_CLOSE;
    }
    return WOLFSSL_CBIO_ERR_GENERAL;
  }

  bool handshake(net::socket_t fd, const std::string& host) {
    // Thread-safe one-time library init (C++11 magic static).
    static const int wolfInit = wolfSSL_Init();
    (void)wolfInit;

    this->fd = fd;

    this->ctx = wolfSSL_CTX_new(wolfSSLv23_client_method());
    if (this->ctx == nullptr) {
      log().error("wolfSSL_CTX_new failed");
      return false;
    }
    wolfSSL_CTX_set_verify(this->ctx, WOLFSSL_VERIFY_NONE, nullptr);
    wolfSSL_CTX_SetIORecv(this->ctx, &TlsSession::ioRecv);
    wolfSSL_CTX_SetIOSend(this->ctx, &TlsSession::ioSend);

    this->ssl = wolfSSL_new(this->ctx);
    if (this->ssl == nullptr) {
      log().error("wolfSSL_new failed");
      return false;
    }
    wolfSSL_SetIOReadCtx(this->ssl, this);
    wolfSSL_SetIOWriteCtx(this->ssl, this);

    if (wolfSSL_UseSNI(this->ssl, WOLFSSL_SNI_HOST_NAME, host.c_str(),
                       static_cast<unsigned short>(host.size())) != WOLFSSL_SUCCESS) {
      log().error("wolfSSL_UseSNI failed");
      return false;
    }

    int r = wolfSSL_connect(this->ssl);
    if (r != WOLFSSL_SUCCESS) {
      int e = wolfSSL_get_error(this->ssl, r);
      char ebuf[WOLFSSL_MAX_ERROR_SZ];
      wolfSSL_ERR_error_string(static_cast<unsigned long>(e), ebuf);
      log().error("wolfSSL_connect failed: %s (err=%d)", ebuf, e);
      return false;
    }

    return true;
  }

  bool sendAll(const void* data, size_t len) {
    const uint8_t* p = static_cast<const uint8_t*>(data);
    size_t off = 0;

    while (off < len) {
      int n = wolfSSL_write(this->ssl, p + off, static_cast<int>(len - off));

      if (n > 0) {
        off += static_cast<size_t>(n);
        continue;
      }

      int e = wolfSSL_get_error(this->ssl, n);

      if (e == WOLFSSL_ERROR_WANT_READ || e == WOLFSSL_ERROR_WANT_WRITE) {
        continue;
      }
      return false;
    }

    return true;
  }

  bool recvExact(void* out, size_t len) {
    uint8_t* p = static_cast<uint8_t*>(out);
    size_t off = 0;

    while (off < len) {
      int n = wolfSSL_read(this->ssl, p + off, static_cast<int>(len - off));

      if (n > 0) {
        off += static_cast<size_t>(n);
        continue;
      }

      int e = wolfSSL_get_error(this->ssl, n);

      if (e == WOLFSSL_ERROR_WANT_READ || e == WOLFSSL_ERROR_WANT_WRITE) {
        continue;
      }
      return false;
    }

    return true;
  }
};
}  // namespace dicker
