#pragma once

namespace dicker {
constexpr const char* kTlsCertPem =
  "-----BEGIN CERTIFICATE-----\n"
  "MIIBeDCCAR6gAwIBAgITC5x3Ebx8HEdRdcpIYv3bFi5njjAKBggqhkjOPQQDAjAR\n"
  "MQ8wDQYDVQQDDAZkaWNrZXIwIBcNMjYwOTE0MTg0ODIyWhgPMjEyNjA4MjExODQ4\n"
  "MjJaMBExDzANBgNVBAMMBmRpY2tlcjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA\n"
  "BAzdAZo2T7egD1a1J4ct+Db5clIdwI4EZYTAXAGlGw3i/mF7AE8EAOxG3g/AvgoQ\n"
  "JZ58XhzSE5hzpCPOE7jnpEejUzBRMB0GA1UdDgQWBBRwJz66NWr2Vrvt+Ih7Zvc2\n"
  "L8aW0TAfBgNVHSMEGDAWgBRwJz66NWr2Vrvt+Ih7Zvc2L8aW0TAPBgNVHRMBAf8E\n"
  "BTADAQH/MAoGCCqGSM49BAMCA0gAMEUCICExXqYRlOhghPXKQWEtsr3w8k2GvOqc\n"
  "pZCVdHzzNJ46AiEA4ZINwtR0zun5HRvVhhzbg5z8vJB15lBuSXSPvx16w+0=\n"
  "-----END CERTIFICATE-----\n";

constexpr const char* kTlsKeyPem =
  "-----BEGIN PRIVATE KEY-----\n"
  "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQggm1jHjNVn4BXe7Bo\n"
  "g00szGl0Zo6VcQoNBJr4NLqFfdOhRANCAAQM3QGaNk+3oA9WtSeHLfg2+XJSHcCO\n"
  "BGWEwFwBpRsN4v5hewBPBADsRt4PwL4KECWefF4c0hOYc6QjzhO456RH\n"
  "-----END PRIVATE KEY-----\n";
}
