#pragma once

#include <cstdint>
#include <cstddef>
#include <vector>

#include <wolfssl/options.h>  // generated by configure; MUST precede other wolfssl headers
#include <wolfssl/ssl.h>

namespace dicker {
struct Connection;

struct TlsLayer {
  WOLFSSL_CTX* ctx = nullptr;
  WOLFSSL* ssl = nullptr;

  // wolfSSL is driven through in-memory buffers instead of a socket: ingest()
  // appends inbound ciphertext to in_buf (consumed by the recv callback from
  // in_pos), and the send callback appends outbound ciphertext to out_buf,
  // which flush_out() drains to the connection.
  std::vector<std::uint8_t> in_buf;
  std::size_t in_pos = 0;
  std::vector<std::uint8_t> out_buf;

  bool handshake_done = false;

  ~TlsLayer();
  bool init();
  void ingest(Connection* connection, const std::uint8_t* data, std::size_t len);
  // Encrypt+send application data, then flush the resulting ciphertext to the
  // connection. Returns false if the TLS write failed. teardown_after is passed
  // through to flush_out (tear the connection down once the bytes are written).
  bool send(Connection* connection, const std::uint8_t* data, std::size_t len,
            bool teardown_after = false);
  void flush_out(Connection* connection, bool teardown_after = false);
};
}
